name: Test

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go: [ 1.14, 1.15, 1.16, 1.17 ]
        postgres: [ 9, 10, 11, 12, 13, 14 ]
        
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Unit test
      run: go test -v ./...
      
    - name: Integration test
      run: cd integration && go test -v ./... -driver 'postgres' -dataSource 'postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable'
